### ISSUE TITLE
CI: Add PEP8 checks

### ISSUE THREAD

**Issue by effigies** [nipype/pydra#10]
Would be good to start off on the right foot, here.

**Comment by satra** [comment]
have been using black, but haven't automated the process.

**Comment by effigies** [comment]
Looks like `black --check` can be used in place of `flake8`.

**Comment by satra** [comment]
let's remove `yapf` configuration and switch to black. it should only be a development dependency not a runtime dependency.

**Comment by djarecka** [comment]
@satra - i added 1pred-commit-config` in this pr: https://github.com/nipype/pydra/pull/58

I'm using `pre-commit`,  so `black` is running on my laptop for every single commit
