### ISSUE TITLE
cache propagation issue on OSX

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#108]
test `test_cache_propagation1` doesn't work on OSX, I believe this is a problem that OSX sets tempdir differently:
`wf.cache_dir` is `PosixPath('/var/folders/32/823z586933zbm26chcmcqq1m0000gp/T/tmpzmou1eal')`
and `t1.cache_dir` is
`PosixPath('/private/var/folders/32/823z586933zbm26chcmcqq1m0000gp/T/tmpzmou1eal')`

**Comment by djarecka** [comment]
yes, remember I was debugging this at some point... It's one of the issue that comes back from time to time and it's always annoying...

**Comment by effigies** [comment]
I think the secret is to release a virus that permanently breaks OSX.

**Comment by djarecka** [comment]
at some point that might be the only solution..;-) One OS to rule them all!

**Comment by satra** [comment]
we could use resolve:

```
(Pdb) wf.cache_dir
PosixPath('/var/folders/sm/488rz12j279_gyxrq7z971zw0000gp/T/tmpymbiqag1')

(Pdb) wf.cache_dir.resolve()
PosixPath('/private/var/folders/sm/488rz12j279_gyxrq7z971zw0000gp/T/tmpymbiqag1')
(Pdb) t1.cache_dir.resolve()
PosixPath('/private/var/folders/sm/488rz12j279_gyxrq7z971zw0000gp/T/tmpymbiqag1')
(Pdb) t2.cache_dir.resolve()
PosixPath('/private/var/folders/sm/488rz12j279_gyxrq7z971zw0000gp/T/tmpymbiqag1')
```

this should work for the tests.
