### ISSUE TITLE
Release 0.1

### ISSUE THREAD

**Issue by satra** [nipype/pydra#131]
version 0.1 is ready for release. any concerns, comments:

cc: / @effigies @mgxd @djarecka

**Comment by effigies** [comment]
Sounds good to me.

**Comment by djarecka** [comment]
sounds goood

**Comment by djarecka** [comment]
@effigies @mgxd - it looks it's time for me to learn how to make a release, but might need some help from you. I should probably start from having access to the PyPI

**Comment by effigies** [comment]
What's your PyPI user?

**Comment by djarecka** [comment]
@effigies - thanks! trying to keep my usernames set small ;-)

**Comment by effigies** [comment]
Good luck. And if your entire release process involves more than `git`, (`python setup.py` or `pip`) and `twine`, you've probably found an out-of-date guide.

**Comment by djarecka** [comment]
@effigies - and do you have your favorite guide?

**Comment by satra** [comment]
favorite guide for this project :)
```
1. update version in a branch and push to github (see versioneer docs)
2. make sure CI pass
3. use annotated git tag with semantic versioning 
4. push `--tags` to make github release
5. use setup.py to build a py3 wheel
6. use twine to push to pypi (note that you can only push one release to pypi - you cannot overwrite a release, you will be forced to update the version)
```

**Comment by effigies** [comment]
No, I'm terrible at collecting useful resources, and I now do this so much that I don't need to look it up. The Software Carpentries might have a good one.

Off of the top of my head, we have the deeply elaborate and in need of pruning [guide to making a nibabel release](https://nipy.org/nibabel/devel/make_release.html#a-guide-to-making-a-nibabel-release), and [nipype's Release checklist](https://github.com/nipy/nipype/wiki/Release-checklist).

And I suppose I should clarify, by release process I mean "tagging, packaging and publishing", which use `git`, `setup.py` and `twine`, respectively.

There's other stuff like updating changelogs, mailmaps, Zenodo metadata, etc. I like to use a release branch for things like that, which gives people a chance to comment if necessary. And for that, I just go find an [old](https://github.com/nipy/nipype/pull/2999) [PR](https://github.com/nipy/nibabel/pull/779) and use it as a template.

**Comment by mgxd** [comment]
@djarecka I aggregated information to a wiki entry here:
https://github.com/nipype/pydra/wiki/Release-Checklist

everyone: feel free to add / change things.

**Comment by djarecka** [comment]
I think I did it, but you can check if everything is ok.

Later today will update the wiki

**Comment by satra** [comment]
overall looks good, but the tag was not annotated. so `git describe` doesn't work.

**Comment by effigies** [comment]
You can delete and repush an annotated tag from the CLI. GitHub takes it pretty smoothly.

**Comment by satra** [comment]
thank you @djarecka  and @effigies

**Comment by djarecka** [comment]
it should be better now. 

@effigies - thanks, but I've changed the tag before reading your answer in full, so I kept the name `0.1`. If you prefer `0.1.0` or `v0.1.0`, let me know

**Comment by effigies** [comment]
Pretty sure 0.1 and 0.1.0 are equivalent as far as PEP 440 is concerned, so I wouldn't worry about redoing it.

**Comment by djarecka** [comment]
ok, I saw people are definitely using this notation, so should be fine

**Comment by djarecka** [comment]
I've updated [wiki](https://github.com/nipype/pydra/wiki/Release-Checklist), feel free to change.

do we want to create zenodo right now, or we will wait wit this?
