### ISSUE TITLE
Remove hard-coded data paths

### ISSUE THREAD

**Issue by effigies** [nipype/pydra#14]
See, e.g.,

https://github.com/nipype/pydra/blob/ce19c71ef8413e8987ac2e4733fb5a0cff4238cf/pydra/engine/tests/test_newnode.py#L1295

https://github.com/nipype/pydra/blob/ce19c71ef8413e8987ac2e4733fb5a0cff4238cf/pydra/engine/tests/test_newnode_neuro.py#L34-L40

We should use datalad or OSF to retrieve data to run tests on.

**Comment by djarecka** [comment]
yes, we probably should create a docker with freesurfer and some data

**Comment by effigies** [comment]
Not fully resolved by #19. Reopening.

**Comment by satra** [comment]
@djarecka - have we removed all tests that depend on fsl and other tools. we should at this point strip out any dependency on nipype or any other neuroimaging package.

**Comment by djarecka** [comment]
and where do you see these dependencies?

**Comment by satra** [comment]
see the original post

**Comment by djarecka** [comment]
but we don't have these tests anymore
