### ISSUE TITLE
tasks connections

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#146]
should we allow for:
1.  connections between tasks without `lzout`, i.e. I want to wait for a previous task without explicitly using its output?

2. should we allow for connections like this: `Task(inp_a=[wf.lzout.out1, wf.lzout.out2])`?

**Comment by satra** [comment]
no for 1. (breaks the definition of a dataflow framework)

2 could be interesting and would obviate some situations, but not high priority at this point.

**Comment by djarecka** [comment]
2. seem to be surprisingly useful, just hacking on testkraken and try various things...

**Comment by satra** [comment]
> 2 seem to be surprisingly useful, just hacking on testkraken and try various things...

does it work out of the box? if so fine. or are you making this work? inserting connections into python containers can get tricky if it doesn't work out of the box

one can also imagine: `inp_a = dict(flag1=wf.lzout.out1, flag2=wf.lzout.out2)` and other possibilities.

**Comment by djarecka** [comment]
your solution doesn't work if you want to have a splitter that includes the list.

**Comment by satra** [comment]
mine isn't a solution to anything, it's just another example. i'm just saying that before this is allowed one has to think about all the situations where one could use outputs into python containers.

**Comment by djarecka** [comment]
@satra ok, sorry, read and answered too quickly. I'd say it's tricky even without containers
