### ISSUE TITLE
kwargs in mark.task functions

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#148]
Might be useful to support functions with kwargs. It might complicate some things, but could be worth it

**Comment by effigies** [comment]
Could you elaborate with a toy example, perhaps?

**Comment by djarecka** [comment]
was thinking about something like this:

```
@pydra.mark.task
def fun_pyd(a, **kwarg):
    out = a
    for i in kwarg.values():
        out += i
    return out
```

Not sure if you want to support or not, but sometimes could be useful.

**Comment by effigies** [comment]
In this case, any connection must be accepted? That's doable, but I haven't really considered what the cost would be in complexity. It may make any tooling that needs to predict whether two nodes can be connected much more difficult, and removing connections would need to be carefully managed.

Another way to imagine accommodating functions like this is to enable re-parametrization with another decorator:

```Python
@pydra.mark.task
@pydra.mark.name(kwargs=['b', 'c', 'd'])
def fun_pyd(a, **kwarg):
    out = a
    for i in kwarg.values():
        out += i
    return out
```

Which would turn this into (without rewriting):

```Python
@pydra.mark.task
def fun_pyd(a, *, b, c, d):
    kwargs = {'b': b, 'c': c, 'd': d}
    out = a
    for i in kwargs.values():
        out += i
    return out
```

This would make these inputs required, so the semantics do change a bit. We could think about a way to preserve their optionality.

This might also make it easier to work with `*args`:

```Python
@pydra.mark.name(args=['a'], kwargs=['b', 'c', 'd'])
def variadic(*args, **kwargs):
    ...

# equivalent to
def concrete(a, *, b, c, d):
    args = [a]
    kwargs = {'b': b, 'c': c, 'd': d}
    ...
```

So we could keep the current, relative simplicity of `mark.task` and use composition to achieve the desired behavior. OTOH, you're unlikely to use a decorator like this on a pre-written function, so I'm not sure it would get used much. I also suspect there is some potential for dynamic, connection-defined inputs to functions being useful. Before diving in, it might be nice to get a concrete case, such as "This enables X idiom for conditionals", but it may be that people won't figure out that use case without the functionality in the first place.

And there's really no reason we can't expand our decorators *and* make `mark.task` handle varargs and kwargs.

So I guess all of this is to say: Maybe?

**Comment by djarecka** [comment]
yes, I agree, that it will add to the complexity and not sure if it's worth it. I like your example `@pydra.mark.name(kwargs=['b', 'c', 'd'])`

**Comment by tclose** [comment]
NB: kwargs are supported in the new syntax
