### ISSUE TITLE
review what should be included checksum

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#155]
for example I'm removing bindings and input that have output_file_template

**Comment by satra** [comment]
- metadata fields that impact future output (e.g. output_field_name)
- we should check if float values are checksummed properly
- make sure nested structures are properly checksummed
- for Path, we will want to checksum related files, so abstracting the file checksum calculation to support related files would be good

**Comment by djarecka** [comment]
@satra - what do you mean by "related files"?

**Comment by satra** [comment]
so in nipype many files are actually sets of files: https://github.com/nipy/nipype/blob/master/nipype/utils/filemanip.py#L29

thus the checksum should be computed over the set.  i think for pydra it would be good if we didn't make assumptions but simply encoded the related set as a list/tuple.

**Comment by satra** [comment]
so having a type that handles related files would be useful to have.

**Comment by djarecka** [comment]
ok, so rather creating a type, than special checksum. Will create an issue for this.

regarding float numbers, do you had something specific in mind? I found this, and I like the solution:
https://docs.python.org/3/library/stdtypes.html#hashing-of-numeric-types

**Comment by djarecka** [comment]
actually, I believe the hash function already uses this approach for float numbers. will just add a test
