### ISSUE TITLE
Convert README.md to RST

### ISSUE THREAD

**Issue by oesteban** [nipype/pydra#164]
With the idea of including it in the ``index.rst`` and use it as long_description in the `setup.cfg` metadata.

**Comment by effigies** [comment]
You can also use m2r to include README.md in an RST document, and set the `long_description_content_type` to `text/markdown` in `setup.cfg`.

**Comment by oesteban** [comment]
I've tried that in fMRIPrep to include the CONTRIBUTING.md in the docs, and didn't success. I might have done something wrong.

Anyways, for the contents we currently have in the README, is it really necessary to have it in markdown?

**Comment by effigies** [comment]
No.

**Comment by djarecka** [comment]
closed with #294
