### ISSUE TITLE
Discussion: attrs vs dataclasses

### ISSUE THREAD

**Issue by effigies** [nipype/pydra#173]
I've spent a bit of time reading through the [attrs documentation](https://www.attrs.org/en/stable), and it looks pretty straightforward and capable of providing much of what we use `traits` for in Nipype 1. And as a pure Python dependency, it seems quite light.

I don't fully understand the problems with dataclasses, though, so I wanted to start a discussion thread where we can work through these issues. The attrs [Why not Data Classes?](https://www.attrs.org/en/stable/why.html#data-classes) section is a bit light on details (though it may be quite clear for someone who's played with them...).

**Comment by djarecka** [comment]
one issue is with pickling, described by Satra here: https://bugs.python.org/issue35510

**Comment by djarecka** [comment]
the second issue I remember is inheritance - the example below does not work and that it's very annoying:
```
@dataclass
class Parent:
    a: str
    b: int = 3

@dataclass
class Child(Parent):
    c: bool

parent = Parent('string', 32)
child = Child('string', 12, c=True)
```

it doesn't even work if I try to overwrite `a`:
```
@dataclass
class Parent:
    a: str
    b: int = 3

@dataclass
class Child(Parent):
    a: str = "ala"
    c: bool

parent = Parent('string', 32)
child = Child('string', 12, c=True)
```

as far as I remember `attrs` has a slightly different way of creating inheritance

**Comment by effigies** [comment]
Was able to do @satra's suggestion without problems using `attr`:

```Python
import attr
import pickle as pk

@attr.s
class A:
    pass

B = attr.make_class('B', [], bases=(A,))

pk.dumps(A)
pk.dumps(B)
```

So agreed that that's an argument for `attrs`.

**Comment by djarecka** [comment]
here is a useful link: https://stackoverflow.com/questions/51575931/class-inheritance-in-python-3-7-dataclasses

`attrs` doesn't solve the problem completely, but it slightly better IMO
