### ISSUE TITLE
Change default `n_procs` arg in `ConcurrentFuturesWorker`

### ISSUE THREAD

**Issue by kaczmarj** [nipype/pydra#177]
What would you like changed/added and why?
- Change the `n_procs` default to the number of CPUs the current process has access to, not the number of CPUs on the machine.

What would be the benefit? Does the change make something easier to use?
- The benefit would be that the CPUs are not oversubscribed.

By default, `n_procs` is set to the number of processors on the machine (that is the default behavior of [concurrent.futures.ProcessPoolExecutor](https://docs.python.org/3/library/concurrent.futures.html#concurrent.futures.ProcessPoolExecutor), but this could oversubscribe the CPUs. Instead, if `n_procs` is `None`, I propose that `n_procs` should be translated to `len(os.sched_getaffinity(0))`, which returns the number of _usable_ CPUs ([documentation](https://docs.python.org/3.8/library/os.html#os.cpu_count)). This would help with things like SLURM, where jobs can be started with access to a subset of CPUs on a machine.

**Comment by effigies** [comment]
Note from [the docs](https://docs.python.org/3.8/library/os.html#interface-to-the-scheduler) (**bold** emphasis added):

> These functions control how a process is allocated CPU time by the operating system. **They are only available on some Unix platforms.** For more detailed information, consult your Unix manpages.
> 
> *New in version 3.3.*
> 
> **The following scheduling policies are exposed if they are supported by the operating system.**

This is not available on my OSX laptop at the moment. So we'll want to make sure we have an appropriate fallback cascade.

**Comment by kaczmarj** [comment]
This might not be possible of macOS. The [`psutil.Process.cpu_affinity()`](https://psutil.readthedocs.io/en/latest/#psutil.Process.cpu_affinity) method is only available for linux, windows, and freebsd.

would it still be useful, on a subset of systems, to set the number of processes based on affinity? not sure if this feature request is worth it.

**Comment by effigies** [comment]
Sure. I just mean something like:

```Python
def get_available_cpus():
    if hasattr(os, 'sched_getaffinity'):
        return len(os.shed_getaffinity(0))
    # Any other methods
    # ...

    # Last resort
    return os.cpu_count()
```

**Comment by kaczmarj** [comment]
`os.shed_getaffinity` is not available on my windows 10 install either. i will submit a pr in the coming days/weeks with an implementation for `get_available_cpus`.

**Comment by djarecka** [comment]
@kaczmarj - are you still thinking about creating a PR?

**Comment by kaczmarj** [comment]
@djarecka - yes, this issue slipped my mind. i will submit a pr soon (tonight or this weekend)
