### ISSUE TITLE
Thoughts from attr conversion - TODOs for next release

### ISSUE THREAD

**Issue by satra** [nipype/pydra#179]
- [x] the hashing code currently assumes flat inputs and will not hash collections containing files properly. see #178, but this is more about `Files` in any type of container (tuple, list, dict) and their nested forms.

- [x] `default_value` metadata should be removed.

- [x] tutorials should be updated before a new release

- [ ] our current dependent projects should be checked (e.g., testkraken)

- [x] we should try to ensure that we are not changing inputs when we run a task/workflow. 

- [ ] push code coverage to 90+ %

-~~[ ] the pickle setstates need some TLC for nested objects. (see ResultSpec)~~

-~~[ ] dask scheduler support~~

- [x] determine how we deal with Undefined vs None.

- ~~[ ] improve sphinx doc using this theme: https://pandas-sphinx-theme.readthedocs.io/en/latest/index.html~~

**Comment by oesteban** [comment]
Just a heads-up

>  improve sphinx doc using this theme

I don't think sphinx versioning would work with that theme

**Comment by effigies** [comment]
Is there a reason we don't want to just stick with ReadTheDocs versioned builds?

**Comment by djarecka** [comment]
I don't have experience with documentation - it would be great if you can point me to the one that should work best (easiest to use or whatever metric is relevant) in your opinion

**Comment by oesteban** [comment]
> Is there a reason we don't want to just stick with ReadTheDocs versioned builds?

As of #161 and #162 if we are to "stick with" something, that would be sphinx-versioning since that is the choice I made to build the documentation (https://nipype.github.io/pydra/). Other than that, there are a couple of equally flimsy reasons:

  - For the last 3 years I've been hearing ReadTheDocs is closing shop next month and that never seems to happen.
  - After the work of Ross getting sphinx-versioning to work well it seems useful to stick with that, and have ownership of the whole deployment via GH pages.

I apologize since I attracted all the attention to probably the lowest priority item in @satra's list.

**Comment by djarecka** [comment]
@oesteban - thank you for the answer! And for the documentation of course! And I'd be very happy  sticking with your choice. Also, if I don't see any strong objections I would also keep the standard theme - maybe I'm too conservative, but I like it :)

**Comment by djarecka** [comment]
@satra 

> * [ ]  we should try to ensure that we are not changing inputs when we run a task/workflow.

do you have a specific example with this issue that you can point me to?

> * [ ]  determine how we deal with Undefined vs None.

you meant that the input variable should be `Undefined` if no value provided by a user?

**Comment by satra** [comment]
> do you have a specific example with this issue that you can point me to?

not at this moment - i made some changes during the attr conversion, but this is more of a principle to keep in mind as we improve tests. we should add some tests on workflows that a copy of wf.inputs before run equals wf.inputs after run.

> you meant that the input variable should be `Undefined` if no value provided by a user?

correct, and should not be included in hash computation. i think setting `default=attr.NOTHING` would achieve the undefined state. so perhaps this should go into documentation more than changing things.

**Comment by djarecka** [comment]
closing this, added #204 for test coverage
