### ISSUE TITLE
Export graph as a diagram

### ISSUE THREAD

**Issue by satra** [nipype/pydra#197]
> What would you like changed/added and why?

Add functionality to export a workflow graph as a diagram similar to nipype's export graph function or tensorboard's graph viewer.

> What would be the benefit? 

Add ability to easily visualize complex workflows.

**Comment by djarecka** [comment]
@satra - you want to implement this with the standard library only?

**Comment by satra** [comment]
yes. we can generate a `dot` file using just standard library (similar to nipype). but the dot file itself could be rendered by [dagre](https://github.com/dagrejs/dagre-d3/wiki#demos) using html + javascript.

**Comment by djarecka** [comment]
ok, so we will be using `dot` standard.language

**Comment by satra** [comment]
i did not fully check that dagre uses dot, but it looked like it.

**Comment by tashrifbillah** [comment]
@djarecka , need help on this?

**Comment by djarecka** [comment]
@tashrifbillah - sure!

**Comment by djarecka** [comment]
Hi @tashrifbillah are you still planning to work on this?

**Comment by tashrifbillah** [comment]
Hi @djarecka , sorry didn't get time, thanks for getting it done. Happy to test in future!
