### ISSUE TITLE
Mapping semantics

### ISSUE THREAD

**Issue by effigies** [nipype/pydra#2]
Suppose we have a function `f(a, b)` and a node:

```Python
nodeA = Node(f, mapper=['a', 'b'])
nodeA.inputs = {'a': ['foo1', 'foo2'], 'b': ['bar1', 'bar2', 'bar3']}
```

Various further steps may occur, but then we have a new function `g(d, e)` such that we wish to map over `e`, and iterate in lockstep with the inputs of `nodeA.a':

```Python
nodeC = Node(g, mapper=('nodeA.a', 'e'))
nodeC.inputs.e = ['baz1', 'baz2']
```

In this case, the `nodeC` instances that are downstream from `nodeA.a == 'foo1'` will receive `e == 'baz1'`. These will continue to map independently of `nodeA.b`.

This would be equivalent to a complete mapper:

```Python
nodeC = Node(g, mapper=[('nodeA.a', 'e'), 'nodeA.b'])
nodeC.inputs.e = ['baz1', 'baz2']
```

### Whiteboard
![20181009_102850](https://user-images.githubusercontent.com/83442/46676344-56742380-cbae-11e8-8063-32ec56972cb2.jpg)

**Comment by satra** [comment]
@djarecka - please check if this has been addressed or should be clarified in documentation.

**Comment by djarecka** [comment]
@satra - it is not addressed, because we decided to take entire mappers/splitters from previous nodes. We could leave this issue open and think about it later
