### ISSUE TITLE
pickle setstates

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#200]
the pickle setstates need some TLC for nested objects. (see ResultSpec)

**Comment by djarecka** [comment]
@satra - i don't remember creating this issue... but I remember talking about this with you, just not sure whether this was before or after removing `dataclass` and what exactly you wanted to achieve

**Comment by satra** [comment]
if you look at result it uses setstate/getstate to handle the output field. if output is further nested objects, it may become more complicated. the intent of this was i think to test and improve pickling of dynamically generated classes. 

indeed this was more of a problem with dataclass, but i could not remove those functions when we refactored to attrs. thus it would be good to understand nested pickling of dynamic attr classes a bit better.
