### ISSUE TITLE
optimize memory usage when splitting

### ISSUE THREAD

**Issue by satra** [nipype/pydra#226]
right now pydra uses up a lot of memory in preparing for submission. we should profile memory usage relative to the number of elements in the splitter. 

we want to minimize the memory footprint over splits. ideally only have copies of inputs as necessary, but not always.

one could also consider optionally caching inputs to disk and reading from disk instead of sending over memory..

**Comment by djarecka** [comment]
`to_job` is mostly to blame. also asyncio method `run_in_executor` leads to significant memory raise, before starting running any task

**Comment by djarecka** [comment]
closed with #246
