### ISSUE TITLE
workers should be run as context managers

### ISSUE THREAD

**Issue by kaczmarj** [nipype/pydra#23]
The relevant workers should be run as context managers so that they clean up properly on exit.

This could be done within the worker object source:

```python
with multiprocess.Pool() as p:
    pass

with concurrent.futures.ProcessPoolExecutor() as p:
    pass

with dask.distributed.Client() as c:
    pass
```

or the worker objects could be made context-aware and run as context managers in Submitter.

```python
with pydra.engine.workers.DaskWorker() as d:
    pass
```

**Comment by satra** [comment]
we have the submitter as a context manager, which is more on the user facing side. workers could be enhanced in the future, but not necessary.
