### ISSUE TITLE
result syntax

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#24]
Should think about the syntax for results for node and workflow with and without mappers. 
What should be the syntax when wf is a node?

This will be important when adding join.

**Comment by satra** [comment]
for the moment consider it all the same. there are some cases where we will have to think more about this.

```
result
-- outputs
-- environment
-- provenance
-- runtime
```

with the possibility that any level of the hierarchy may be piped through. so the entire result to any sub keys.  for the moment you can focus on just outputs, but the details will change as i work on the base classes.

**Comment by effigies** [comment]
Supposing I have a node:

```Python
n = Node(callable, inputs={...}, output_names=['a', 'b', 'c'])
```

Then its outputs:

```Python
>>> n.run()
>>> n.results
{'a': <someval>,
 'b': <someval>,
 'c': <someval>}
```

I would say that if there's any un-collapsed state, the default behavior for results for the original node is to just combine it, similar to a `MapNode`:

```Python
>>> n = Node(callable, inputs={'x': [1, 2, 3], 'y': float},
             output_names=['a', 'b', 'c'], split='x')
>>> n.run()
>>> n.results
{'a': [<a|x==1>, <a|x==2>, <a|x==3>],
 'b': [<b|x==1>, <b|x==2>, <b|x==3>],
 'c': [<c|x==1>, <c|x==2>, <c|x==3>]}
```

If I want to get things by state, then maybe something like:

```Python
>>> n._subnodes[0].state
{'n.x': 1}
>>> n._subnodes[0].results
{'a': <a|x==1>,
 'b': <b|x==1>,
 'c': <c|x==1>
}

**Comment by effigies** [comment]
I agree, in general we probably don't want to return state unless very explicitly asked. To be clear `<a|x==1>` is just shorthand for a value, not a state object.

**Comment by djarecka** [comment]
Not sure what do you mean "for the moment consider it all the same". I think I shouldn't completely mixed results if you have mappers. But we can come back to the discussion when I have `combiner`.

I can add option to not print the input, right now I always keep the state

**Comment by satra** [comment]
@djarecka - i'm assuming this is now resolved. please close if so.

**Comment by djarecka** [comment]
yes, we're not returning states in the result
