### ISSUE TITLE
only final set output is kept

### ISSUE THREAD

**Issue by satra** [nipype/pydra#252]
this works
```python
wf.set_output([("output", wf.fit_clf.lzout.output),
                ("auc", wf.fit_clf.lzout.auc)])
```
but this doesn't
```python
wf.set_output([("output", wf.fit_clf.lzout.output)])
wf.set_output([("auc", wf.fit_clf.lzout.auc)])
```

**Comment by djarecka** [comment]
i'm not sure if i think about it as a bug... but if you think, this should be changed I could do it

**Comment by satra** [comment]
you can, and should, raise an error if the output key is already connected, but it is much easier to set output when you add the specific task to a workflow rather than in one go at the end of a workflow.

**Comment by satra** [comment]
also this would allow someone who imports a workflow to connect additional outputs.

**Comment by djarecka** [comment]
ok, makes sense
