### ISSUE TITLE
Node API and execution model

### ISSUE THREAD

**Issue by effigies** [nipype/pydra#26]
Trying to think through the execution model, I think a useful distinction will be between graph nodes and execution nodes. Graph nodes would be aware of the graph structure and their own state:

```Python
class Node:
    def __init__(self, runnable, inputs=None, split=None, combine=None):
        self._parents = []
        self._runnable = runnable
        self._inputs = inputs or {}
        self._state = State(self, split, combine)

    def add_parent(self, node):
        self._parents.append(node)

    @property
    def state(self):
        return self._state.resolve([parent.state for parent in self._parents])

   def get_execution_nodes(self):
        return [ExecutionNode(self._runnable, inputs={self._inputs, **state_inputs})
                for state_inputs in self.state.generate_inputs()]

    def run(self):
        for execnode in self.get_execution_nodes():
            if execnode.ready:
                execnode.run()
```

I would treat `ExecutionNode`s ephemerally. Their inputs should implement some kind of future/promise interface, and their outputs should be loadable from file, such that:

```Python
>>> execnode1 = node.get_execnodes()[0]
>>> execnode1.run()
>>> execnode1.results
{'out_a': <a>,
 'out_b': <b>}
>>> execnode2 = node.get_execnodes()[0]
>>> execnode2 is execnode1
False
>>> execnode2.inputs.in_a is execnode1.inputs.in_a
True
>>> execnode2.results
{'out_a': <a>,
 'out_b': <b>}
>>> os.remove_dirs(execnode2._results_path)
>>> execnode1.results
RuntimeError("Node not run")
```

This approach to `Node` leads to each node storing a partial `State` object that is only fully resolved at runtime, when all of its parents are known. If we have a sensible pairwise combination semantics for state, we can do the following:

```Python
class State:
    @classmethod
    def merge(cls, state_a, state_b, context):
        if state_a is state_b:
            return state_a
        if not state_b.axes:
            return state_a
        if not state_a.axes:
            return state_b
        # create a new state from two states, using current state's splits
        # to assist in reordering

    def resolve(self, states):
        if states == []:
            return self

        state = states[0]
        for tmp_state in states[1:] + [self]:
            state = self.merge(state, tmp_state, self._split)
        return state
```

It needs fleshing out, but the idea is that `resolve` will return the most recently changed `State` object, where changing means adding, removing, or reordering axes. Calling for inputs from the states will check to make sure that the shapes of inputs match, when needed.

I have some other thoughts as to how execution falls out of here, but I'll let those percolate for a bit. In the meantime, what do y'all think? Does this simplify/complicate how we're currently thinking of nodes? I do think it's a significantly different approach to state, so I don't want to charge ahead without feedback.

**Comment by djarecka** [comment]
@effigies - I'm trying to finish `combine` part. Happy to come back to this discussion afterward.

**Comment by satra** [comment]
i'm going to close this as we have the new API implemented. there is room for optimization, but the current engine works.
