### ISSUE TITLE
Can't run tutorials locally

### ISSUE THREAD

**Issue by jsmentch** [nipype/pydra#272]
Running Pydra version I think 0.6 but it says 0+unknown, I installed with pip install pydra. Running in a singularity image on cent OS. pydra-ml is working fine so I think it is installed correctly.

I was trying to use pydra to find umap hyperparameters but can't get splitters to work and the tutorials don't work locally. It hits a lot of `RuntimeError: This event loop is already running` Maybe things have been updated a lot since whenever the tutorial was made.

example from tutorial 3:
```
import pydra

@pydra.mark.task
def add_two(x):
    return x + 2

task1 = add_two(x=[1, 2, 3])

task1.split("x")

task1()
task1.result()

---------------------------------------------------------------------------
RuntimeError                              Traceback (most recent call last)
<ipython-input-7-06d1102645a1> in <module>
----> 1 task1()
      2 task1.result()

~/.local/lib/python3.7/site-packages/pydra/engine/core.py in __call__(self, submitter, plugin, rerun, **kwargs)
    356         if submitter:
    357             with submitter as sub:
--> 358                 res = sub(self)
    359         else:
    360             if is_workflow(self):

~/.local/lib/python3.7/site-packages/pydra/engine/submitter.py in __call__(self, runnable, cache_locations, rerun)
     57             self.loop.run_until_complete(self.submit_workflow(runnable, rerun=rerun))
     58         else:
---> 59             self.loop.run_until_complete(self.submit(runnable, wait=True, rerun=rerun))
     60         if is_workflow(runnable):
     61             # resetting all connections with LazyFields

/opt/miniconda-latest/lib/python3.7/asyncio/base_events.py in run_until_complete(self, future)
    568         future.add_done_callback(_run_until_complete_cb)
    569         try:
--> 570             self.run_forever()
    571         except:
    572             if new_task and future.done() and not future.cancelled():

/opt/miniconda-latest/lib/python3.7/asyncio/base_events.py in run_forever(self)
    523         self._check_closed()
    524         if self.is_running():
--> 525             raise RuntimeError('This event loop is already running')
    526         if events._get_running_loop() is not None:
    527             raise RuntimeError(

RuntimeError: This event loop is already running
```
-->

**Comment by djarecka** [comment]
@jsmentch - is it possible that you haven't python environment using the tutorial [requirements](https://github.com/nipype/pydra-tutorial/blob/master/requirements.txt)?
Do you know what version of `tornado` you have?

There are some known issue with jupyter and newer tornado library.

**Comment by PeerHerholz** [comment]
Hi @jsmentch and @djarecka,

I just tried it on my local machine, as well as binder and things work fine there. Did you run it in a notebook? Chances are re-running cells created the problem?
Could you maybe try it within a "fresh" environment (e.g. `conda create -n pydra python==3.7 && conda activate pydra && pip install pydra`)?

**Comment by djarecka** [comment]
@PeerHerholz - I'm guessing that you have an older version of `tornado`. Could you please double check.
We decided to move tutorial from `pydra` repository, and the `tornado` also has been removed, so you're likely installed `tornado` with something else.

**Comment by PeerHerholz** [comment]
I installed `pydra` via `pip` within a new `conda env` as stated above. Within that new environment I checked the tutorials.

**Comment by djarecka** [comment]
hmm.. how did you check the tutorials? you didn't install jupyter?

**Comment by PeerHerholz** [comment]
ah sorry, yeah: installing the respective versions of `tornado` and `notebook` as indicated in the tutorial `requirements.txt` is necessary.

**Comment by djarecka** [comment]
it's really annoying, but hasn't been fixed...https://github.com/jupyter/notebook/issues/3397

**Comment by jsmentch** [comment]
I'm definitely missing some of those requirements, missed that file! I will give it another go after installing those, thanks

**Comment by jsmentch** [comment]
Yup, it was due to missing requirements, seems to be working now!

Maybe it would be helpful for new users to mention in the readme or the notebooks somewhere that there are these requirements (even though I do see that requirements file now) I just assumed it had the same requirements as pydra

**Comment by djarecka** [comment]
@jsmentch - you're right. Could you open an issue or create PR in the pydra-ML repo?
will close this one

**Comment by satra** [comment]
@djarecka  - i don't think you meant pydra-ML right? this is about this repo.

**Comment by djarecka** [comment]
sorry, was thinking about pytra-tutorial!
