### ISSUE TITLE
Replace __file__ with pkg_resources to make the package zip-safe

### ISSUE THREAD

**Issue by effigies** [nipype/pydra#282]
If we use `__file__`, that has to be installed as a directory. But the main reason to do this is to do something like `Path(__file__).parent / "data" / "blah"`, which is what `pkg_resources.resource_filename` exists for, and is compatible with zipped installations.

This will just add some flexibility and might make it easier to do something like a `py2exe` thing.

**Comment by effigies** [comment]
Note that this only works for data that is packaged. We currently have some testing data that is not packaged as part of an sdist/wheel.

**Comment by satra** [comment]
in pydra-ml i was using this explicit thing.

https://github.com/nipype/pydra-ml/blob/master/setup.cfg#L43

**Comment by effigies** [comment]
So we're not avoiding packaging test data? I noticed a [10MB NIfTI](https://github.com/nipype/pydra/blob/master/pydra/engine/tests/data_tests/test.nii.gz).

**Comment by satra** [comment]
ah, we should not have any nifti's in pydra at all. i think this is a function of the early bet example. we should just remove it from pydra.
