### ISSUE TITLE
Suggestion: Reduce Travis queue

### ISSUE THREAD

**Issue by effigies** [nipype/pydra#285]
Looking at the Travis queue, I suspect I set it up. We have seven of each Python 3.7 and 3.8, and a total of 20 jobs (2 allowed failures).

I think we can reduce this.

* `python setup.py install/develop`: Because we install extras with `pip install [-e] ".[extra]"`, these don't really get tested, anyway, so we should at least figure out how to test these cases better, or just drop them. It's not clear there are cases where testing a `pip` installation would succeed and these would fail.
* `sdist`/`wheel`: These should get tested iff we distribute them. For a pure Python package, we could safely move to distributing only wheels, and just drop `sdist` from consideration.
* Minimum installation dependencies: Maybe just on Python 3.7? The features we depend on predate Python 3.8. It seems safe to say that testing these constraints with the assumption that somebody who doesn't regularly update pip/setuptools also isn't regularly updating Python.
* Minimum requirements: We should definitely keep this, but it looks like we're not actually doing that installation. This is bad, as it means we can't see when we break declared compatibility.
* Style: Let's just do this with one version. I would say with the latest Python, because we don't really care to test `black`'s handling of old Pythons.
* I didn't have anything to do with the others, so I'll assume they're all sensible. :-)

**Comment by satra** [comment]
since we also have travis and circle and azure, this may be another instance of switching to github actions (if it allows docker-based tests - i haven't checked that).

**Comment by effigies** [comment]
Circle is just doc builds. Does it make sense to just enable RTD pull request checks?

**Comment by effigies** [comment]
@satra Do you want to enable? Or add me as an admin on RTD?

**Comment by satra** [comment]
add you as maintainer

**Comment by effigies** [comment]
RTD enabled. Screenshot in case it's helpful in other repositories:

<img width="1099" alt="Screen Shot 2020-06-17 at 09 24 14" src="https://user-images.githubusercontent.com/83442/84903715-709d1f00-b07c-11ea-814e-3b3234d7cdc3.png">

**Comment by effigies** [comment]
Oh, weird. We're actually hosting something that looks a lot like RTD on nipype.github.io/pydra/. I thought it was a redirect.

**Comment by satra** [comment]
i think @oesteban  was pushing it from the circleci builds

**Comment by effigies** [comment]
So should we drop RTD altogether? I don't really understand the process now.

**Comment by satra** [comment]
i don't think oscar's thing can generate a PR-specific build and post it on gh-pages. while it sounds like rtd can host PR builds and send a link to PRs. so for PRs that may be good.

**Comment by oesteban** [comment]
PR-specific builds are done, we would just need to post them to gh-pages. But, if you just want to visualize them, CircleCI does just fine.

**Comment by satra** [comment]
@oesteban - i should have been clearer. this is more about how the outputs are reported back to the user on github. i was looking for the ideal scenario, a build happens and a link is posted in the PR. so that the user doesn't have to go to circleci and find the artifacts. and when the PR is merged, of course on a push to the master branch, the docs pages should be updated.

i believe all of this could be achieved through github actions and may simplify the stuff related to the CIs.

**Comment by oesteban** [comment]
Oh, I haven't played with GA to do this - the artifacts are zipped into a file you must download (don't know if there's a way of changing that).

With circle, there's this github app that can be configured to add one link to the summary of every PR
