### ISSUE TITLE
reviewing docs directory, adding inputs spec

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#306]

**Comment by PeerHerholz** [comment]
Any takers? Given I could ask for further information, I would be happy to work on this.

**Comment by satra** [comment]
@PeerHerholz - if you take this on, could you please take a crack at switching to [myst](https://myst-parser.readthedocs.io/en/latest/). obviously comes with the notions of using a new thing, but i'm sure many will be thankful for any bugs we find.

you can always ask for more info !

also we will likely be switching this to github action-based building and deploying to github pages as well.

**Comment by PeerHerholz** [comment]
There's always something new, eh? Sure thing, happy to try out something new and from a first brief glimpse it loos doable. So basically, the entire docs should be converted to myst? 
I assume the switch to GitHub actions + pages will be coordinated by you or @djarecka, eh?

**Comment by satra** [comment]
@nicolocin is taking the first stab at converting the tests to github actions, once that is merged we can move the docs to it. there are example workflows of doc building and pushing to github in both reproschema and dandi/handbook

**Comment by satra** [comment]
first thing to evaluate is if all the docs including the api side can be converted to myst. the purpose of myst was slightly different than api docs, so worth checking out first.

**Comment by PeerHerholz** [comment]
Ok, I will start checking the docs asap!

**Comment by PeerHerholz** [comment]
So, I checked a bunch of things and think that the switch should be possible. In case we encounter problems along the way, we could rely on `.rst` till it's solved on the `myst` side as it supports `md` and `rst` parsing.
