### ISSUE TITLE
Pydra workflow takes unreasonably long time when given a large input list to split

### ISSUE THREAD

**Issue by Hoda1394** [nipype/pydra#349]
I am trying to run a job in parallel with pydra so I give it an input list to split on and I noticed that it takes unreasonably long for the job to be done. I created the following test workflow to reproduce the issue and check the time consumed for different input lengths. 

```
import pydra
from pydra.utils.messenger import AuditFlag, FileMessenger
import numpy as np

@pydra.mark.task
def show_var(a):
	print("This var is: {}".format(a))
	return a

def generate_list(l):
	return np.arange(l).tolist()

wf=pydra.Workflow(
	name="wf",
	input_spec=["x"],
	cache_dir="wf_tmp_dir",
	audit_flags=AuditFlag.PROV,
	messengers=FileMessenger(),
)

wf.split("x", x=generate_list(5000))
wf.add(show_var(name="show",a=wf.lzin.x))
wf.set_output([("out", wf.show.lzout.out)])

message_path ="wf_mss_dir/messages"
wf.audit.messenger_args=dict(message_dir=message_path)

with pydra.Submitter(plugin="cf", n_procs=20) as sub:
    sub(wf)
```
Here is the timing I measured for various input lengths:
input length           time
20                            5 sec
40                            5sec
100                          10 sec
500                          01:23 min
1000                        07:08 min
2000                        52:50 min
4000                        09:39:23 hrs
5000                        14 hrs (edited) 

As you can see in the code, I am using `plugin="cf", n_procs=20`. So, for input lengths more than 1000 it should not be that long.
Pydra version: 0.6

**Comment by djarecka** [comment]
@Hoda1394 - I've noticed that you are using an older version of pydra. I don't have any specific reason to believe that in the current version it should work faster, but would you mind updating pydra and checking if the time is similar for one of the simulations (e.g. the one for 2000)

**Comment by Hoda1394** [comment]
@djarecka - I rerun the code above with pydra version 0.9 for 2000 and I got the same timing (01:03:57). Also, I tried different input lengths with `n_procs=1` which should be serial execution and I got similar times.
input.       time
5		00:00:05
10		00:00:04
20		00:00:05
40		00:00:04
100		00:00:12	
200		00:00:16
500		00:00:46
1000        00:05:52
2000	00:45:19
4000	09:05:52		
5000	14:17:52

**Comment by djarecka** [comment]
@Hoda1394 - thanks for checking! Looks like the biggest issue is with collecting all results together, but still debugging

**Comment by satra** [comment]
even just 200 -> 500 shows an exponential growth. just tracking that down should resolve the others.

**Comment by djarecka** [comment]
@satra - at the end I haven't changed too much in #353, but might think in future to do it better

I was also considering of removing results collecting when running the workflow - i.e. removing this [line](https://github.com/nipype/pydra/blob/master/pydra/engine/submitter.py#L63). We can still think about it, it would not change the time of collecting the results (#353 does change this), but would just remove it, so you would have to ask after running for `wf.result()`

**Comment by satra** [comment]
@djarecka - can you post the timing changes here with the changes in code? does it solve the issue? are we in linear time scale?

**Comment by djarecka** [comment]
yes, it is linear (or almost linear) now. Definitely it fixes one important issue that was in the `checksum_states`, there might be still others, that I will try to find. 
These are times for the example I was using yesterday (locally):

 size  | before | after
 250  |      29  |    20
 500  |      96  |    40
1000 |    687  |    83
2000|   4539 |  180

**Comment by satra** [comment]
thanks @djarecka - that's great.

**Comment by djarecka** [comment]
@satra - perhaps I could merge my PR, make a minor release and let @Hoda1394 test?

**Comment by satra** [comment]
sounds good. let's also test the publishing process with the minor release. so just send a tag to master and let me try releasing.

**Comment by Hoda1394** [comment]
@djarecka- Great, I will happily test that :)

**Comment by djarecka** [comment]
@Hoda1394 - it hasn't been released on PyPI website, but if you want to test you can always install from the master branch

**Comment by Hoda1394** [comment]
I tested it with 2000 and 4000 input length and comparing to previous timing the difference is huge!
2000/ 00:02:51
4000/ 00:06:57

**Comment by djarecka** [comment]
@Hoda1394 - so happy to hear this! btw. 0.9.1 is already available on PyPI

Thanks for reporting! Closing this for now.
