### ISSUE TITLE
consider removing testing pip 10.0.1

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#352]
right now the [allow failure workflow](https://github.com/nipype/pydra/blob/master/.github/workflows/testallowfail.yml) contains pip 10.0.1 installation and it fails for windows.

If there are no plans to fix it, I'd remove it and improve the requirements info in README.

@effigies - I believe you added `10.0.1` to travis testing at some point. Do you think we should still care about this version of pip?

**Comment by satra** [comment]
@effigies - i know you are super busy - any memory of why this specific pip version was added?

**Comment by effigies** [comment]
Sorry, yes, I saw this but then 300 other notifications piled on top. That version is the lowest I could find that respects `pyproject.toml` and uses build isolation (or possibly the highest I could find that doesn't). The idea of the set of install-time dependencies was to make sure we're resilient to either old setuptools or old pip.

If it's causing problems, I wouldn't worry too much. Anybody installing from source should have a more recent version. If it becomes an issue, we can re-titrate the versions and explicitly declare our minimum supported versions.

**Comment by djarecka** [comment]
thanks @effigies , so I'll remove it this for now.
