### ISSUE TITLE
make pydra testing work with pytest 6.0+

### ISSUE THREAD

**Issue by satra** [nipype/pydra#359]
currently pydra testing runs only on pytest versions less than 6 and with pytest-xdist < 2. most folks are going to move to pytest 6+ and will not want to downgrade pytest just for pydra.

::aside
also it may be worthwhile considering the install procedure for testing. when testing min-requirements, `pip install .[test]` could override those requirements because of testing dependencies. so it may be useful to break tests down into:
- minimal tests 
- numpy tests
- tests boutiques (also now that we have a decent task framework in place, do consider whether boutiques is pulled out into its own package)

**Comment by djarecka** [comment]
i've added `pytest-xdist < 2` when was some issues with compatibility on travis. Will try to remove the requirement.
