### ISSUE TITLE
big memory use for workflows

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#371]
The problem was originally reported by @Hoda1394 and I'm currently testing suing this kind of workflows:

```
@mark.task
def show_var(a):
    return a

def generate_list(l):
    my_list = np.arange(l).tolist()
    return my_list

wf= Workflow(name="wf", input_spec=["x"])
wf.split("x", x=generate_list(size))
wf.add(show_var(name="show", a=wf.lzin.x))
wf.set_output([("out", wf.show.lzout.out)])
wf()
```

So I do see a non-linear (quadratic?) relation between memory and the size of the list. I decided to rely mostly on the RSS memory measure from GNU time, and here is a plot:
![rss_wf](https://user-images.githubusercontent.com/1662746/96677046-c5a7b500-133c-11eb-89d2-9c40b558a36d.png)

This is a workflow related issue, I've tested tasks with a splitter and the relation is linear.

I've been struggling to debug it, but I got to a point that I think I know where the problem is generated, but not sure why. It could be also that I'm simply missing something else. I've modified `submit` method to add a simple print statement (wrapped in a coroutine) to `futures` instead of `worker.run_el` (see [here](https://github.com/djarecka/pydra/blob/tmp_testmem_2.1/pydra/engine/submitter.py#L137)) and this single modified line still leads to increase the memory. Any thoughts? (cc:@satra, @mgxd )

**Comment by satra** [comment]
can you try setting `self.output_ = None` after this line: https://github.com/nipype/pydra/blob/master/pydra/engine/core.py#L446

also both task._run and workflow._run should ideally have very little change in the size of self. you may want to check memory before and after each step. 

also take a look at the recent profiler PR in nipype. perhaps that profiler can be used here.
