### ISSUE TITLE
Implement container execution

### ISSUE THREAD

**Issue by satra** [nipype/pydra#38]
Related to #32 

Minimal task support currently merged. should be extended to provide complete isolation. i should be able to run the pydra workflow itself in one container, and have it launch other tasks inside that container or in remote containers (through slurm, aws, dind, singularity, etc.,.)

**Comment by satra** [comment]
- [ ] run entire workflow using one container
- [ ] run each task and sub workflows using the prescribed container for the workflow
- [ ] run each task in its own prescribed container
- [ ] propagate new environment from one task to next
- [ ] add semantics for overrides both downstream and upstream (may result in exceptions when in conflict

**Comment by djarecka** [comment]
> * [ ]  propagate new environment from one task to next
- propagate new environment from one task to next

do you mean passing `image`? Image is an input, so you can a make connection

> * [ ]  add semantics for overrides both downstream and upstream (may result in exceptions when in conflict

could you please elaborate

**Comment by satra** [comment]
i think these two tasks could be punted for later. 

yes, the first one would allow setting the environment of a subsequent task from the output of a previous task. something like.

`task2.image = task1.lzout.image`

for downstream and upstream this gets more complicated. let's say i set the workflow to run tasks using a container. should this override the container of a subtask that has an explicit container? so we need options for workflow overrides task, or task overrides workflow.

**Comment by djarecka** [comment]
#202 shows that the image can be treated as any other input, so can be also part of the connection.

I've added one more point - `FunctionTask` with a container has to be done before we can propagate image to each task of the wf

**Comment by djarecka** [comment]
for now we are not working for this anymore, will keep the missing points for later
