### ISSUE TITLE
pip install -e .[dev] Update README

### ISSUE THREAD

**Issue by chasejohnson3** [nipype/pydra#385]
I am new to contributing to pydra, and in the Developer installation instructions, pydra can be installed in developer mode using
`pip install -e .[dev]`
This syntax does not work in mac zsh, as identified here: [pip install -e .[dev] error in mac zsh](https://github.com/mu-editor/mu/issues/852#issuecomment-498759372). They suggest `pip install -e ".[dev]"` works universally.

I suggest the following changes to the pydra README:
`pip install -e .[dev]` -> `pip install -e ".[dev]"`
`pip install -e .[dask]` -> `pip install -e ".[dask]"`

I would be happy to make this change as my first PR if these changes are desired.

**Comment by chasejohnson3** [comment]
If the above suggestions are accepted, I have implemented the changes above in PR #386.

**Comment by effigies** [comment]
#386 merged. Thanks!
