### ISSUE TITLE
output_spec field types not implemented

### ISSUE THREAD

**Issue by chasejohnson3** [nipype/pydra#387]
What version of Pydra are you using?
0.12

What were you trying to do?
Pass a parameter of type Directory (or anything other than File) into the output_fields of an output_spec for a pydra task.

What did you expect will happen?
I expect to make fields in an output_spec with varying types. In particular: Int, Float, File, Bool, Str, Directory, and List.

What actually happened?
When all output_spec fields are of the type File, the task runs as expected. When any other type is introduced, the task stops and the following error message is shown.
`Error: “Exception: not implemented (collect_additional_output)”`

Can you replicate the behavior? If yes, how?
Yes, the following task is an adaptation to the pydra tutorial 5_intro_shelltask and throws the error
 `Error: “Exception: not implemented (collect_additional_output)”`

```
import nest_asyncio
nest_asyncio.apply()
import pydra
import attr

cmd = "echo"
args = ["newfile_1.txt", "newfile_2.txt"]

my_output_spec = pydra.specs.SpecInfo(
    name="Output",
    fields=[
        (
            "out1",
            attr.ib(
                type=pydra.specs.File,
                metadata={
                    "output_file_template": "{args}",
                    "help_string": "output file",
                },
            ),
        ),
        (
            "outDir",
            attr.ib(
                type=pydra.specs.Directory, # Causes error!
                metadata={
                    "output_file_template": "output_directory",
                    "help_string": "The directory for output to be written",
                },
            ),
        ),
    ],
    bases=(pydra.specs.ShellOutSpec,),
)

shelly = pydra.ShellCommandTask(name="shelly", executable=cmd, args=args, output_spec=my_output_spec).split("args")

print("cmndline = ", shelly.cmdline)

with pydra.Submitter(plugin="cf") as sub:
    sub(shelly)
shelly.result()
```

How I found the error:
I was running a pydra task generated from a Slicer Execution Model for [BRAINSToolsBrainsConstellationDetector](https://github.com/BRAINSia/BRAINSTools/tree/master/BRAINSConstellationDetector). One of the output fields had type pydra.specs.Directory and caused the error. The task ran to completion when this field was removed from the output_spec (all other output fields had type pydra.specs.File).

Location of the error:
In pydra/pydra/engine/specs.py in class ShellOutSpec under collect_additional_outputs. 
there is a conditional statement where only types File and MultiOutputFile are currently supported as output types.
```
if fld.type in [File, MultiOutputFile]:
        ...
else:
        raise Exception("not implemented (collect_additional_output)")
```

Is anyone working on implementing additional types in output_spec fields? If not, I can start working on it.

**Comment by djarecka** [comment]
@chasejohnson3 - yes, I was planning to implement more types, especially for `Directory`, but not working on this right now, so would be great if you can work on this. Thank you!

**Comment by chasejohnson3** [comment]
Great! I'll get started on adding more types.

**Comment by chasejohnson3** [comment]
Currently, File and MultioutputFile are implemented as follows:
```
if fld.type in [File, MultiOutputFile]:
                    # assuming that field should have either default or metadata, but not both
                    if (
                        fld.default is None or fld.default == attr.NOTHING
                    ) and not fld.metadata:  # TODO: is it right?
                        raise AttributeError(
                            "File has to have default value or metadata"
                        )
                    elif fld.default != attr.NOTHING:
                        additional_out[fld.name] = self._field_defaultvalue(
                            fld, output_dir
                        )
                    elif fld.metadata:
                        additional_out[fld.name] = self._field_metadata(
                            fld, inputs, output_dir
                        )
```
Should there be different logic for different datatypes, or can we just catch all data types we want and apply the same logic?
i.e. `if fld.type in [File, MultiOutputFile]:` -> `if fld.type in [File, MultiOutputFile, Directory, Int, Float, Bool, Str, List]:`

**Comment by djarecka** [comment]
let me take a step back - one thing is to add `Directory` to the list, but I wonder if we need int, floats, etc. Wouldn't this be part of the `stdout` for the `ShellCommandTask`?

**Comment by satra** [comment]
one can process stdout or some output file and return something else. for example see fslstats:

https://github.com/nipy/nipype/blob/54f502940/nipype/interfaces/fsl/utils.py#L811

but in general any task should be able to output any set of fields.

**Comment by djarecka** [comment]
@satra - well, but from shell tasks we could have only what is in `stdout` and what is created on the disk, so files/directories. The only way to get int from the shell task would be if the int is written in `stdout` (or `stderr`). So do you want to have special `callable`s that would take `stdout` and `stderr` and returns whatever the user define?

**Comment by satra** [comment]
> So do you want to have special callables that would take stdout and stderr and returns whatever the user define?

yes. that is what we did for fslstats and some other nipype interfaces. but more generally since list_outputs could read any file and parse in anyway that interface felt useful to propagate. so not just stdout/stderr. (e.g., some output could be the length of a list of files produced the shell task)

**Comment by djarecka** [comment]
@chasejohnson3 - so in the place you pointed out, it's likely that all types could be added, but `callable` should be required in the `metadata`

**Comment by chasejohnson3** [comment]
I added the types discussed to the list of accepted output_spec field types. A callable is required in the metadata for any field with type Int, Float, Bool, Str, or List. These changes can be found in PR #389. Let me know if this correctly implements the changes discussed above.
