### ISSUE TITLE
cannot specify output file name

### ISSUE THREAD

**Issue by chasejohnson3** [nipype/pydra#395]
What version of Pydra are you using? 
0.12.1

What were you trying to do?
I am trying to specify the name of a file by adding the filename in both the input_spec and output_spec.

What did you expect will happen?
I would expect to be able to specify the file name (and even a parent directory) for a file.

What actually happened?
An error was thrown: `FileNotFoundError: the file from the outputFile input does not exist`

Can you replicate the behavior? If yes, how?
Yes, the following code snippet throws the error with the input_spec and output_spec as I described above.

```
import nest_asyncio
nest_asyncio.apply()
import pydra
import attr

cmd = "echo"

my_input_spec = pydra.specs.SpecInfo(
        name="Input",
        fields=[
            (
                "outputFile",
                attr.ib(
                    type=pydra.specs.File,
                    metadata={"help_string": "The name of a file to be created.", "mandatory": True},
                ),
            )
        ],
        bases=(pydra.specs.ShellSpec,),
    )

my_output_spec = pydra.specs.SpecInfo(
        name="Output",
        fields=[
            (
                "outputFile",
                attr.ib(
                    type=pydra.specs.File,
                    metadata={
                        "help_string": "The output file",
                        "output_file_template": "{outputFile}"
                    },
                ),
            ),
        ],
        bases=(pydra.specs.ShellOutSpec,),
    )



shelly = pydra.ShellCommandTask(name="shelly", executable=cmd, input_spec=my_input_spec, output_spec=my_output_spec)
shelly.inputs.outputFile = "out_file.txt"

print("cmndline = ", shelly.cmdline)

with pydra.Submitter(plugin="cf") as sub:
    sub(shelly)
print(shelly.result())
```
Throws:
`FileNotFoundError: the file from the outputFile input does not exist`

Is there a better way to specify a file name? If not, I would think the requirement for an input_spec file to exist should be removed or a flag be added indicating an input_spec field should create a file rather than access an existing one.

**Comment by djarecka** [comment]
Whatever is in `InputSpec` with `File` type, it has to be an existing file. I should improve the documentation for it, but for now I can give you an example from my tests:
- you can have `outputFile` in the `input_spec` as a str with `output_file_template` (it will be automatically added to the `output_spec` when the template is used) - [see this](https://github.com/nipype/pydra/blob/master/pydra/engine/tests/test_shelltask.py#L1013)
- or you can add `outputFile` with `output_file_template` to the `output_spec` - [see this](https://github.com/nipype/pydra/blob/master/pydra/engine/tests/test_shelltask.py#L3008)

**Comment by chasejohnson3** [comment]
That is exactly what I was looking for! Thank you for pointing me to those tests.
