### ISSUE TITLE
Iterable input to pydra workflow

### ISSUE THREAD

**Issue by chasejohnson3** [nipype/pydra#400]
Is it possible to pass a nipype iterable into a pydra workflow?

For example:
I found an iterable example from an old nipype issue [iterable with Node](https://github.com/nipy/nipype/issues/2311)

```
from nipype import Function, Node, Workflow
from nipype.interfaces.utility import IdentityInterface

ii = Node(IdentityInterface(fields=['a', 'b']), name="test")                                                                                                                                 
ii.inputs.a = 4
ii.iterables = [("b", [1,4])]

def add_numbers(x, y):
    return x + y

adding = Node(Function(input_names=["x", "y"],
                           output_names=["sum"],
                       function=add_numbers),
              name='add_numbers')

wf = Workflow(name="test_iterable")
wf.connect([(ii, adding, [("a", "x"), ("b", "y")])])
res = wf.run()

print(list(res.nodes())[0].result.outputs)
print(list(res.nodes())[1].result.outputs)
```
Could I make a pydra task to add2 to the output of the Node `adding`? If so, what would that look like?

**Comment by satra** [comment]
@chasejohnson3 - i'm not sure i'm fully following here. nipype nodes and pydra tasks won't mix. but that script can be implemented in pydra (and pydra does not need the concept of identityinterface - it's effectively built into the Workflow task)

but pydra has full support for iterables. we have essentially combined all of nipype's semantics with iterables/joinnode/mapnode into pydra splits/combine. if you haven't gone through the pydra tutorials that may help.

**Comment by chasejohnson3** [comment]
The fact that pydra tasks don’t mix with nipype nodes and iterables are implemented in pydra splits answers my question. Thanks for the feedback!
