### ISSUE TITLE
Serial Workflow Outputs

### ISSUE THREAD

**Issue by chasejohnson3** [nipype/pydra#403]
I want to run a workflow (wf) on a list of outputs coming from a source node (source). The results should handle each element of the list independently. I am working with the following script:

```
import pydra
import nest_asyncio
nest_asyncio.apply()

@pydra.mark.task
def add2(x):
    return x + 2

@pydra.mark.task
def multiply(x, y):
    return x*y

source = pydra.Workflow(name="source", input_spec=["x"])
source.add(add2(name="add2", x=source.lzin.x))
source.set_output([("out", source.add2.lzout.out)])
source.split("x")
source.inputs.x = [1, 2]

wf = pydra.Workflow(name="wf_st_3", input_spec=["x"])
wf.add(source)
wf.add(add2(name="add2", x=wf.source.lzout.out))
wf.add(add2(name="add2again", x=wf.add2.lzout.out))
mult = multiply(name="mult2", x=wf.add2again.lzout.out, y=wf.add2.lzout.out)
wf.add(mult)
wf.set_output([("add2", wf.add2.lzout.out),
               ("add2again", wf.add2again.lzout.out),
               ("mult2", wf.mult2.lzout.out)])

with pydra.Submitter(plugin="cf") as sub:
    sub(wf)
results = wf.result()
print(results)
```
with output
`Result(output=Output(add2=[5, 6], add2again=[7, 8], mult2=[35, 42, 40, 48]), runtime=None, errored=False)`

I would like the output to be
`Result(output=Output(add2=[5, 6], add2again=[7, 8], mult2=[35, 48]), runtime=None, errored=False)`
where the first and second elements of x are treated separately in wf.

How can I achieve this behavior?

**Comment by chasejohnson3** [comment]
Here is something that achieves the intention behind this question. The variable x in node wf is set to`x=source.lzin.x` and all computation is performed in wf. This only partially solves my problem, as I would like to do some computation in the source node before passing the results of source to wf, but the end result correctly separates the output of 35 and 48.

```
import pydra
import nest_asyncio
nest_asyncio.apply()

@pydra.mark.task
def add2(x):
    return x + 2

@pydra.mark.task
def multiply(x, y):
    return x*y

@pydra.mark.task
def get_num(x):
    return x

source = pydra.Workflow(name="source", input_spec=["x"])
wf = pydra.Workflow(name="wf", input_spec=["x"], x=source.lzin.x)
source.add(wf)
source.split("x")
source.inputs.x = [1, 2]

wf.add(add2(name="add2_1", x=wf.lzin.x))
wf.add(add2(name="add2_2", x=wf.add2_1.lzout.out))
wf.add(add2(name="add2_3", x=wf.add2_2.lzout.out))
wf.add(multiply(name="mult2", x=wf.add2_3.lzout.out, y=wf.add2_2.lzout.out))
wf.set_output([("mult2",  wf.mult2.lzout.out)])

source.set_output([("mult2",  source.wf.lzout.mult2)])


with pydra.Submitter(plugin="cf") as sub:
    sub(source)
results = source.result()
print(results)
```

`[Result(output=Output(mult2=35), runtime=None, errored=False), Result(output=Output(mult2=48), runtime=None, errored=False)]`

If there is a way to do some computation in the source node before passing the results into wf, I would appreciate the insight but if not, this issue can be closed.

**Comment by satra** [comment]
is this what you mean?

```python
source = pydra.Workflow(name="source", input_spec=["x"])

compute = wf.add(some_compute(name="compute", x=source.lzin.x))
wf = pydra.Workflow(name="wf", input_spec=["x", "y"], x=source.lzin.x, y=compute.lzout.somevar)

source.add(wf)
```

**Comment by chasejohnson3** [comment]
@satra yes that does what I was intending, thank you.
