### ISSUE TITLE
Possible deadlock when splitting at workflows

### ISSUE THREAD

**Issue by jw-96** [nipype/pydra#444]
I found a way to create a deadlock in Pydra.

Pydra version: 0.14.1, 
Python version: 3.9.2
In a jupyter notebook.

I was working on translating this [tutorial](https://miykael.github.io/nipype_tutorial/notebooks/example_preprocessing.html) into Pydra. For which I created two workflows an inner and an outer one. The outer workflow has a splitter on three arguments. When trying to run the workflow, I noticed how it starts out with all 8 virtual cores of my machine being utilized 100%, but after a few minutes, they were all at idle again without the cell having finished executing. Upon closer observation, I noticed that they seem to go idle in pairs, which made me think of a deadlock. 

The output when stopping the cell showed a process getting interrupted when trying to acquire a lock, which confirmed my suspicion. 

I replicated the deadlock in a smaller example program because the tutorial consists of many nodes and needs a dataset. 
Together with the output, it is available [here]( https://github.com/neurorepro/pydra-glm-example/blob/main/other/Deadlock.ipynb ).

```Python
import nest_asyncio
nest_asyncio.apply()

import pydra

task_list = ["First", "Second"]
start_list = [1,2,3,4,5,6,7,8]

@pydra.mark.task 
def one_arg(start_number):
    print(start_number)
    for k in range(100000000):
        start_number += 1
    return start_number

@pydra.mark.task 
def two_num(a, b):
    print(a, b)
    a = a + b
    for k in range(100000000):
        a += 1
    return a


@pydra.mark.task 
def fin_node(a, b, task_name):
    print(a, b, task_name)
    return a+b

# Outer workflow
test_outer = pydra.Workflow(name="test_outer", input_spec=["start_number", "task_name"])
# Splitting on both arguments
test_outer.split(["start_number", "task_name"], start_number = start_list, task_name = task_list)

# Inner Workflow
test_inner = pydra.Workflow(name="test_inner", input_spec=["start_number1"])
test_inner.add(one_arg(name = "Ilevel1", start_number = test_inner.lzin.start_number1))
test_inner.set_output([("res", test_inner.Ilevel1.lzout.out)])



# Outer workflow has two nodes plus the inner workflow
test_outer.add(one_arg(name = "level1", start_number = test_outer.lzin.start_number))
test_outer.add(test_inner)
test_inner.inputs.start_number1 = test_outer.level1.lzout.out




# The second node takes as input the output of the first node and the inner workflow
test_outer.add(fin_node(name = "level4", a = test_outer.level1.lzout.out, b =\
       test_outer.test_inner.lzout.res, task_name = test_outer.lzin.task_name))
test_outer.set_output([("res", test_outer.level4.lzout.out)])

with pydra.Submitter(plugin="cf") as sub:
    sub(test_outer)

test_outer.result()
```

I think that the deadlock occurs because the outer splitting happens at the beginning of the workflow for the two arguments, but only the last node uses the second argument (task_name). In my example, the second argument contains two entries. Therefore, all nodes of the workflows will be run twice in different processes each using the same input from the first argument (start_number). So these two processes would then be competing to lock the same cache directory, because node name and inputs are the same. 

The deadlock can easily be worked around by moving the splitting from test_outer to the last node (level4).  

I am not sure if a deadlock like this should be prevented by Pydra or if it should be up to the user to detect and prevent it. In any case, I thought to let you know about it.

**Comment by djarecka** [comment]
@jw-96 - thanks for reporting. Looks like you had a case that was not covered by my tests - with splitter that is not used and the inner workflow at the same time. I was able to reproduce and I've been trying to solve it but hasn't finished yet.  looks like it is stuck in `exec_as_coro`, but not sure why... will come back to this later in the week

**Comment by jw-96** [comment]
I found an even smaller minimal example that does not need two workflows.  A list containing duplicate items will cause a deadlock if it is split up. I think the deadlock happens for the same reason as in my other example, which is why I am posting this here as an update.

pydra version 0.14.1
```
import pydra

text = ["test"] * 2

@pydra.mark.task 
def printer(a):
    print(a)
    return a
    
wf = pydra.Workflow(name="wf", input_spec=["text"])
wf.split(("text"), text = text)

wf.add(printer(name = "printer1", a = wf.lzin.text))

wf.set_output([("out1", wf.printer1.lzout.out)])

with pydra.Submitter(plugin="cf", n_procs=6) as sub:
    sub(wf)

print(test_outer.result(return_inputs=True))
```
This example also breaks the fix on which I was working for the previous deadlock example. I tried to integrate a workflows inputs into all its nodes when calculating the checksums, but this approach will not fix this deadlock.

**Comment by jw-96** [comment]
The problem seems to be with the filelock. It never gets past acquiring the lock. I switched them out for [fasteners](https://pypi.org/project/fasteners/) locks. With them one of the tasks is able to acquire the lock while the other waits. However, it looks like the process that acquired the lock crashes at some point without resting the cwd. The second task then acquires it and also crashes because a os.getcwd() causes an error.

**Comment by djarecka** [comment]
Thanks @jw-96 , for now I'm testing on this example:
<details>

```
def test_1(tmpdir):
    task_list = ["First", "Second"]
    start_list = [3]

    @task
    def one_arg(start_number):
        print("\n START", start_number)
        for k in range(10):
            start_number += 1
        return start_number

    @task
    def one_arg_inner(start_number):
        print("\n START inner", start_number)
        for k in range(10):
            start_number += 1
        return start_number

    print("\n TMPDIR", tmpdir)

    # Outer workflow
    test_outer = Workflow(
        name="test_outer", input_spec=["start_number", "task_name"], cache_dir=tmpdir
    )
    # Splitting on both arguments
    test_outer.split(
        ["start_number", "task_name"], start_number=start_list, task_name=task_list
    )

    # Inner Workflow
    test_inner = Workflow(name="test_inner", input_spec=["start_number1"])
    test_inner.add(one_arg_inner(name="Ilevel1", start_number=test_inner.lzin.start_number1))
    test_inner.set_output([("res", test_inner.Ilevel1.lzout.out)])

    # Outer workflow has two nodes plus the inner workflow
    test_outer.add(one_arg(name="level1", start_number=test_outer.lzin.start_number))
    test_outer.add(test_inner)
    test_inner.inputs.start_number1 = test_outer.level1.lzout.out

    test_outer.set_output([("res2", test_outer.test_inner.lzout.res)])

    with Submitter(plugin="cf") as sub:
        sub(test_outer)

    res = test_outer.result()
    print("RES, ", res)
```
</details>


And I discovered that [this](https://github.com/nipype/pydra/blob/master/pydra/engine/specs.py#L93) is the line that leads to the issue. But it is not about the code in the `if` and `else` blocks, it is about checking `inspect.stack()[1][3]` itself...
@satra @effigies - any idea?

**Comment by satra** [comment]
`stack()[1][3]` seems magical. is that just hanging?

also in your test example, any particular reason you create a second identical function (except for its name)?

and thank you @jw-96 for the simple example. @djarecka - i thought we had a test of this nature somewhere. a split on a list containing similar values.

**Comment by djarecka** [comment]
it's even worse than hanging there...
If I modify `__setattr___` to this simple form:
```
    def __setattr__(self, name, value):
        print("BEFORE")
        print(inspect.stack()[1][3])
        print("AFTER")
        super().__setattr__(name, value)
``` 
my output is:
```
...
BEFORE
__init__
AFTER
BEFORE
__attrs_post_init__
AFTER
```

**Comment by djarecka** [comment]
as far as the @jw-96 example from yesterday - I'm not sure if this is exactly the same issue (seems to be unrelated to `inspect.stack()[1][3]`), but I can confirm that something is wrong, will be checking. Also thought that we have a similar example. Will be checking this.

@satra - and yes two function in my example do the same, added just for debugging, will remove

**Comment by jw-96** [comment]
I did a small sanity check on the example from yesterday. I added these three lines before the [locking](https://github.com/nipype/pydra/blob/bbe0a28748aedca8bad087b5f2a64adf5b2bf8d0/pydra/engine/core.py#L1010): 
```
wait = random.randint(1, 9)
print(wait)
await asyncio.sleep(wait)
```
And it finishes.

Without sleep, it stops at this [asyncio wait](https://github.com/nipype/pydra/blob/bbe0a28748aedca8bad087b5f2a64adf5b2bf8d0/pydra/engine/workers.py#L51). The ```exec_as_coro``` of ```printer1``` is never executed. It does not even start it. It just hangs at the wait.

**Comment by jw-96** [comment]
I found this issue [#78](https://github.com/benediktschmitt/py-filelock/issues/78) on the py-filelock GitHub page. Maybe, It is the reason for the deadlock.

**Comment by jw-96** [comment]
Yes, applying the suggested workaround fixed the deadlock for me. Both examples now work. I will work on a pull request tomorrow.

**Comment by djarecka** [comment]
For my example adding this random wait helps (as removing `inspect.stack()[1][3]`), but I'm not sure if we can add this kind of waits... I've checked that adding just `wait(1)` doesn't help, it really has to be randomized, so possibly it would have to be even more than `9` for other examples :(

**Comment by jw-96** [comment]
With the suggested workaround I meant the one described in  [#78](https://github.com/benediktschmitt/py-filelock/issues/78). I replaced the [locking](https://github.com/nipype/pydra/blob/bbe0a28748aedca8bad087b5f2a64adf5b2bf8d0/pydra/engine/core.py#L1010) with:
```
    lock = SoftFileLock(lockfile)
    acquired_lock = False
    while not acquired_lock:
        try:
            lock.acquire(timeout=0)
            acquired_lock = True
        except Timeout:
            await asyncio.sleep(1)
```
and imported the Timout from filelock. The last change was adding ```lock.release()``` where the ```with``` block would end.

**Comment by djarecka** [comment]
oh, ok. let's try. I'm still don't fully understand the issue
