### ISSUE TITLE
Codecov security breach

### ISSUE THREAD

**Issue by mgxd** [nipype/pydra#448]
https://about.codecov.io/security-update/

We are using the bash uploader here
https://github.com/nipype/pydra/blob/233b51c8faa114cb20b7d8d48ecc4b37257ed8bf/.github/workflows/testslurm.yml#L19

> We strongly recommend affected users immediately re-roll all of their credentials, tokens, or keys located in the environment variables in their CI processes that used one of Codecov’s Bash Uploaders.

**Comment by effigies** [comment]
I have revoked the `PYPI_USERNAME` and `PYPI_PASSWORD` secrets. Whoever created them (I think @nicolocin) needs to change their password ASAP.

**Comment by effigies** [comment]
I've also removed user `nlo` as a maintainer of the package, on the assumption that she is the person whose user/password were potentially exposed.

Prior to the next release, we need to switch to a token-based upload.

**Comment by satra** [comment]
i believe the token based approach uses those `PYPI*` variables (with a special user `__token__`). since the values are hidden, you probably did not get to see that.

**Comment by effigies** [comment]
Okay. Whoever created the token needs to revoke and re-create it. I would suggest moving to this action to be a bit more direct: https://github.com/pypa/gh-action-pypi-publish

**Comment by satra** [comment]
sent a PR #449

**Comment by effigies** [comment]
Re-invited user nlo as maintainer.
