### ISSUE TITLE
Nipype vs Pydra Caching

### ISSUE THREAD

**Issue by chasejohnson3** [nipype/pydra#476]
This is a question just to get a better understanding of the differences between Nipype v1 and Pydra.

Is there caching in Nipype v1 workflows? As I understand it, one of the major improvements pydra offers above Nipype v1 is caching and its ability to reproduce a result without rerunning an entire workflow.

However, I have seen a Nipype v1 workflow implemented with some form of caching, and I am trying to figure out if this is a built-in feature of Nipype v1 or if the creator of the workflow implemented caching themselves separate from Nipype.

**Comment by satra** [comment]
Nipype 1 indeed has caching. The user does not have to do anything, other than point nipype to a folder that can be used as a cache.

But
- the caches cannot be shared across workflows
- the same operations within a workflow cannot reuse the cache
- whole workflows cannot be cached

Pydra supports all of these use cases.
