### ISSUE TITLE
Workflow Exception Not Caught

### ISSUE THREAD

**Issue by chasejohnson3** [nipype/pydra#488]
What version of Pydra are you using?
0.16.2

What were you trying to do?
I am running a workflow containing a task that raises an exception in some cases.

What did you expect will happen?
I would expect the workflow to run to completion for all non-erroring paths through the workflow and the output associated with the errored task(s) to be errored=True.

What actually happened?
The workflow raises an exception and stops execution. No results are generated from the workflow.

Can you replicate the behavior? If yes, how?

The following code replicates the behavior described above:
```
@pydra.mark.task
def error_3(x):
    if x == 3:
        print(f"{x} (error)")
        raise Exception("x was 3")
    else:
        print(f"{x}")
        return x

wf = pydra.Workflow(
    name="wf",
    input_spec=["x"],
    x=[1, 2, 3, 4, 5, 6, 7, 8, 9],
).split("x")
wf.add(error_3(name="error_3", x=wf.lzin.x))
wf.set_output([("out", wf.error_3.lzout.out)])

wf()
print(wf.result())
```

Actual Output:
```
1
2
3 (error)
Task exception was never retrieved
future: <Task finished name='Task-6' coro=<ConcurrentFuturesWorker.exec_as_coro() done, defined at /Shared/sinapse/pydra-cjohnson/pydra/pydra/engine/workers.py:160> exception=Exception('x was 3')>
concurrent.futures.process._RemoteTraceback:
"""
Traceback (most recent call last):
  File "/Users/cjohnson30/anaconda3/lib/python3.8/concurrent/futures/process.py", line 239, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
  File "/Shared/sinapse/pydra-cjohnson/pydra/pydra/engine/core.py", line 465, in _run
    self._run_task()
  File "/Shared/sinapse/pydra-cjohnson/pydra/pydra/engine/task.py", line 183, in _run_task
    output = cp.loads(self.inputs._func)(**inputs)
  File "wf_exception.py", line 36, in error_3
    raise Exception("x was 3")
Exception: x was 3
"""
```

Expected output:
```
1
3 (error)
2
[Result(output=Output(out=1), runtime=None, errored=False), 
Result(output=Output(out=2), runtime=None, errored=False), 
Result(output=Output(out=None), runtime=None, errored=True)]
```

I would think a workflow should not be stopped and prevented from returning a result due to a single task's exception, but I should ask about the intended implementation. 

Is it intended the entire pipeline stops execution due to an exception, or should the error just be reported in the results?

**Comment by djarecka** [comment]
@chasejohnson3 - not this is not intended behavior, checking this now

**Comment by djarecka** [comment]
This is an issue not only for workflow, but also for  a task with splitter. 

At some point we were discussing that if one element of the task returns an error, we should still continue running workflows for other elements, but we haven't finished the implementation.
The expected output you suggested looks reasonable to me, but I was wondering if we still shouldn't return error at the end of the task or workflow, i.e. run all elements, bur raise an error at the end.

@satra @effigies - any thoughts?

**Comment by chasejohnson3** [comment]
@djarecka Do you have an idea of how the solution of this issue may be implemented? I tried looking into several ways of catching exceptions in `_run_workflow` in `submitter.py` but was unable to get the workflow to continue execution after an exception was caught.
