### ISSUE TITLE
`Workflow` constructor raises `TypeError` when `input_spec` is an instance of `SpecInfo`

### ISSUE THREAD

**Issue by NicolasGensollen** [nipype/pydra#572]
The documentation of the `Workflow` constructor says that `input_spec` can be a list of strings, a `SpecInfo`, or a `BaseSpec` instance:

https://github.com/nipype/pydra/blob/219c72170984f013eeb1fdc3d87f1d4a58d0dfab/pydra/engine/core.py#L807

However, when providing a `SpecInfo` I get a `TypeError: unhashable type: 'SpecInfo'`.

Looking at the code, it seems like this case isn't handled properly such that we end up iterating over the `SpecInfo` instance (line 860), triggering the error described above:

https://github.com/nipype/pydra/blob/219c72170984f013eeb1fdc3d87f1d4a58d0dfab/pydra/engine/core.py#L843-L863

 It *could* be that `SpecInfo` was supposed to inherit from `BaseSpec`, but it doesn't seem to be the case atm:

https://github.com/nipype/pydra/blob/219c72170984f013eeb1fdc3d87f1d4a58d0dfab/pydra/engine/specs.py#L65

**Comment by satra** [comment]
@NicolasGensollen - this seems like an oversight and is a bug. 

would you like to send a PR to resolve this ? i think the only specific check that would be needed is that the `SpecInfo` object has `BaseSpec` as it's bases, similar to the constructor here: https://github.com/nipype/pydra/blob/219c72170984f013eeb1fdc3d87f1d4a58d0dfab/pydra/engine/core.py#L862

**Comment by NicolasGensollen** [comment]
@satra Sure I'll send a PR! Thanks for the quick reply ! 👍
