### ISSUE TITLE
run node workflow without creating submitter

### ISSUE THREAD

**Issue by kaczmarj** [nipype/pydra#6]
it would be handy to be able to create a `Node` or `Workflow` instance and then run it with `.run(*args, **kwds)`.

**Comment by djarecka** [comment]
running Node/Workflow by calling `Submitter.run()` was a @satra suggestion, at least for a temporary solution

**Comment by satra** [comment]
@djarecka, @mgxd - is this now available?

**Comment by mgxd** [comment]
@satra all tasks are callable, i.e.

```python
@to_task
def foo(x):
    return x + 7

a = foo(x=1)
a()
```
will return `Result(output=Output(out=8), runtime=None, errored=False)`.

Though, workflows are not properly handled at the moment - I'll add a quick fix.

**Comment by djarecka** [comment]
@mgxd - it should be also added to tests

**Comment by djarecka** [comment]
do we want tasks with splitter to be callable? 
It is not supported right now...

**Comment by satra** [comment]
> do we want tasks with splitter to be callable?

yes

**Comment by djarecka** [comment]
@satra - i should  have ask question "do we want tasks with splitter to be callable using `_run` without creating submitter?".

**Comment by satra** [comment]
if it's possible to do without extreme mechanics ( i.e. 30 mins or less of work), then yes

**Comment by satra** [comment]
@mgxd, @djarecka - is this now done?

**Comment by mgxd** [comment]
@satra i addressed this within #64 (47f7a3d2bea058ca7259736d861bbbccc53c33fb)

once slurm testing is implemented, i'll upgrade it from a draft

**Comment by satra** [comment]
closed via #64
