### ISSUE TITLE
developer installation doc needs to be updated

### ISSUE THREAD

**Issue by yibeichan** [nipype/pydra#615]
in Readme, Developer installation is illustrated as the following:
```
Pydra requires Python 3.7+. To install in developer mode:
git clone git@github.com:nipype/pydra.git
cd pydra
pip install -e ".[dev]"
```

However, after the recent update, `setup.cfg` has been removed; instead, `pyproject.toml` has been used.
`pip install -e ".[dev]"` needs to be updated. So does `pip install -e ".[dask]"`

Happy New Year!

**Comment by effigies** [comment]
I'm not seeing what the issue is. Does `pip install -e ".[dev]"` not work for you? What version of pip are you using?

**Comment by yibeichan** [comment]
Yes! I got this error
```
ERROR: File "setup.py" or "setup.cfg" not found. Directory cannot be installed in editable mode: /Users/yibeichen/GDrive/GitHub/pydra
(A "pyproject.toml" file was found, but editable mode currently requires a setuptools-based build.)
```
my pip version is `pip 21.2.2 from /Users/yibeichen/miniconda3/envs/pydra/lib/python3.7/site-packages/pip (python 3.7)`

**Comment by ghisvail** [comment]
You need at least Pip version [21.3](https://pip.pypa.io/en/stable/news/#v21-3) which supports PEP-610.

**Comment by yibeichan** [comment]
thank you! well I just realized that I can upgrade pip and try it again. So I did... and it works.....

**Comment by ghisvail** [comment]
I am used to running `pip install --upgrade pip` whenever I instantiate a new virtual environment, so I had to look it up to find the exact version which introduced the necessary support.

**Comment by yibeichan** [comment]
Thanks for the tips! I had this conda env last summer and didn't upgrade it for a while...
