### ISSUE TITLE
missing dependencies for tests

### ISSUE THREAD

**Issue by kaczmarj** [nipype/pydra#63]
For the Bug Report,
Include this information:
-------------------------
What version of Pydra are you using? 
- `0.0.1+298.g759ec5d`
What were you trying to do? 
- run tests
What did you expect will happen?
- tests to mostly pass
What actually happened?
- tests failed due to missing dependencies
Can you replicate the behavior? If yes, how? 
- run `make test` in a fresh conda environment after having installed pydra with `pip install --editable .`

List the steps you performed that revealed the bug to you.
Include any code samples. Enclose them in triple back-ticks (```)
Like this:

```bash
conda create -n pydra python=3.7
conda activate pydra
cd /path/to/pydra
pip install --no-cache-dir --editable .[tests]
make test
```

Dependencies that are missing:
- numpy
- psutil
- dask and distributed

Should the plugin dependencies be added to the 'tests' extra?

**Comment by djarecka** [comment]
we can add them for now to tests, but we will be removing them soon anyway

**Comment by kaczmarj** [comment]
i guess if they will be removed soon, it doesn't make much sense to add them now
