### ISSUE TITLE
Networkx-Dask DAG API?

### ISSUE THREAD

**Issue by dPys** [nipype/pydra#72]
@satra -- I've been working on the profiler (i.e. via network flow optimization using a combo of dask + networkx) and am wondering if you already have an API on hand for formatting networkx-based DAG's in dask-friendly format (see: https://docs.dask.org/en/latest/optimize.html#definitions and https://docs.dask.org/en/latest/custom-graphs.html)? If not I can/will write one?

Not sure what your thoughts are on DAG optimization using dask, but it offers considerable flexibility: https://docs.dask.org/en/latest/optimize.html#customizing-optimization. Curious to get your thoughts...

@dPys

**Comment by satra** [comment]
@dPys  - for the current pydra, we are pure python only with no dependencies. 

dask will be available as an optional worker dependency. regarding optimization, we will have to look into it. splits and combines make it harder to do certain types of optimizations. 

dask won't be able to run our complex DAGs (nested workflows as well as splits and combines) efficiently. so the pydra engine will be required.

@djarecka is putting together a set of notebooks for a user playground. once that is ready, you should at least be able to play with the concepts to see if they work for you.

**Comment by dPys** [comment]
@satra - thanks for the heads up, and I'm glad that I asked. 

I am very intrigued by your comment RE: "splits and combines make it harder to do certain types of optimizations" and would be curious to learn why when the time comes. In the meantime, I should mention that I was lucky enough to sit next to @stsievert on an airplane a few days ago. He PR's quite heavily to dask and we spoke a bit about how dask handles DAG optimization/profiling. Is there currently a pydra prototype for the optional dask worker API? If so, I'd be eager to tinker with it. If not, I'd be eager to help start it.

Otherwise, looking forward to playing with some of the concepts from @djarecka 's notebooks.
@dPys

**Comment by stsievert** [comment]
> on DAG optimization using dask, but it offers considerable flexibility

There's also flexibility in determining how that DAG is executed through Dask Distributed: https://distributed.dask.org/en/latest/scheduling-policies.html (which I neglected to mention).

**Comment by satra** [comment]
@dPys and @stsievert - we fully intend to support dask as a pydra `Worker` right after we get the execution of our current API set (99% there). 

regarding optimization it truly boils down to what the DAG is and the requirements for execution (typically use case and domain dependent).  pydra's focus is generally on running tasks that require significant file i/o and using tools written by a diverse group of developers (not necessarily in python). also pydra's semantics allow nested DAGs (a node of DAG can be a DAG) and for any Task it can be operationalized to map over a set of splits on inputs (various combinations).

once @djarecka's notebooks are ready, we would really like for you to play with them and then think about ways to improve dask support and optimization. @djarecka had already implemented a dask worker, which has been temporarily removed, but will reappear soon.

**Comment by dPys** [comment]
Perfect @satra . Will be ready to tinker when @djarecka has finished the notebooks.

@stsievert -- Any other Dask developers come to mind who might be working with custom DAGs and/or DAG optimization in particular? Maybe when the time is right, we could loop them in too.

Cheers,
@dPys

**Comment by djarecka** [comment]
yes, will let you know when I have the notebooks!

**Comment by stsievert** [comment]
> Any other Dask developers come to mind who might be working with custom DAGs and/or DAG optimization in particular? Maybe when the time is right, we could loop them in too.

Hm... I think they should be in the loop too, but I'm certainly not the person to ask. I'd ask on the Gitter channel, http://gitter.im/dask/dask. They'll know more. https://github.com/dask/dask/issues/4038, https://github.com/dask/dask/pull/2608 and https://github.com/dask/dask/pull/3549 might be good resources.

> pydra's semantics allow nested DAGs (a node of DAG can be a DAG)

Thanks. I've done some digging, and it turns out Dask also has a tool for nested DAGs: https://docs.dask.org/en/latest/high-level-graphs.html. There's been a lot of recent work on optimization with this nested or "high level" graphs (e.g., https://github.com/dask/dask/pull/4229).

**Comment by dPys** [comment]
Thanks @stsievert for the resources. I had a feeling that something like high-level DAGs in dask might be available for handling at least some of the nesting features of pydra. 

More soon,
@dPys

**Comment by stsievert** [comment]
> I had a feeling that something like high-level DAGs in dask might be available for handling at least some of the nesting features of pydra.

I hope the high-level DAG feature works for you! 

If not, I'd probably contact @mrocklin, @jcrist or @jakirkham for more information on high-level graph optimization. They can all be reached through the Dask gitter channel (http://gitter.im/dask/dask) I think.

**Comment by satra** [comment]
@dPys @stsievert - the tutorials are up and running. here is the binder link:

https://mybinder.org/v2/gh/nipype/pydra/master?filepath=tutorial%2Fnotebooks

**Comment by dPys** [comment]
Thanks @satra for posting these! 

I noticed that DaskWorker has now been removed, so would be curious to hear whether the plan is just to incorporate that down the road once everything else is stable (i.e.if/when dask's role in pydra is more clearly defined)? Seems to me that the primary benefit of a dask worker would be workflow resource optimization should it be possible to cleanly track/store auditing information throughout the pydra DAG and then interface with dask's high-level DAG functionality for the actual optimization...

Curious to hear your thoughts.
@dPys

**Comment by satra** [comment]
@dPys - we wanted to clear up some basic scenarios before bringing dask worker back. hopefully we will do a release soon alongside the tutorials and then get to work on dask worker and other optimizations.

**Comment by dPys** [comment]
Ah, makes sense, will keep an eye out for that then.

In the meantime, I am currently trying to figure out how to keep runtime resources with the audit flag saved to each respective node of the DAG. Flow optimization, in or outside of a dask context (e.g. pure networkx), will be easier when this information, along with hard-coded load capacities are stored as node/edge attributes (in the main DAG or a separate accompanying DAG) that can be readily queried.

@dPys

**Comment by satra** [comment]
> I am currently trying to figure out how to keep runtime resources with the audit flag saved to each respective node of the DAG.

you can get that by loading the result file (or `node.result()`)

**Comment by satra** [comment]
we have recreated the dask worker in #242 . overall it seems to work and you should be able to use it by simply setting the plugin arg of the submitter to "dask" (and installing dask, distributed).

```
    with Submitter("dask", **dask_client_args) as sub:
        sub(wf)
```
`dask_client_args` should allow you to connect to distributed schedulers, but can be left out to create a local cluster.

however there are connected cross-repo problems we need to solve:
- testing lots of dask tasks using pytest seems to be running into scheduler communication errors at least on travis
- for dask, the tornado version cannot be 4.5.3, which is what we need for testing jupyter notebooks with asyncio

more generally, i would love to figure out a better interaction, because there are definitely dask elements being developed that are directly related to nested graphs, but none of them support the split-combine semantics of pydra.

**Comment by dPys** [comment]
> we have recreated the dask worker in #242 . overall it seems to work and you should be able to use it by simply setting the plugin arg of the submitter to "dask" (and installing dask, distributed).
> 
> ```
>     with Submitter("dask", **dask_client_args) as sub:
>         sub(wf)
> ```
> 
> `dask_client_args` should allow you to connect to distributed schedulers, but can be left out to create a local cluster.
> 
> however there are connected cross-repo problems we need to solve:
> 
> * testing lots of dask tasks using pytest seems to be running into scheduler communication errors at least on travis
Out of curiosity, what errors in particular does it log? Could you post a link to the specific failed build in this thread?
> * for dask, the tornado version cannot be 4.5.3, which is what we need for testing jupyter notebooks with asyncio
Is this because of event-loop nesting? Have you tried nest_asyncio?
> 
> more generally, i would love to figure out a better interaction, because there are definitely dask elements being developed that are directly related to nested graphs, but none of them support the split-combine semantics of pydra.
Is this where pytest runs into issues? Or is it that when you feed a split or combine to the submitter the dask Client returns an error?

**Comment by stsievert** [comment]
> testing lots of dask tasks using pytest seems to be running into scheduler communication errors at least on travis

Here's the test structure that's used by Dask-ML when the client is required:

``` python

> testing lots of dask tasks using pytest seems to be running into scheduler communication errors at least on travis

Here's the test structure that's used by Dask-ML when the client is required:

``` python
from distributed.utils_test import gen_cluster
import dask.array as da
import numpy as np

@gen_cluster(client=True, timeout=5000)
def test_basic(c, sched, w1, w2):
    x = np.random.rand(10)
    x_dask = da.from_array(x)
    x_dask *= 2
    y = yield c.compute(x_dask)
    assert np.allclose(2 * x, y)
```

In Dask-ML, this is used with pytest on Azure Pipelines. In Distributed, it's used with pytest on Travis.

> `with Submitter("dask", **dask_client_args) as sub:`

Can I create a `Submitter` object from a Dask cluster I've configured myself? This could enable the test issue to be resolved, and also provide more usability. It looks to be possible after glancing at `DaskWorker`: https://github.com/nipype/pydra/blob/acc90101af22637ff71139224441eacd08b14452/pydra/engine/workers.py#L315-L318

```

In Dask-ML, this is used with pytest on Azure Pipelines. In Distributed, it's used with pytest on Travis.

> `with Submitter("dask", **dask_client_args) as sub:`

Can I create a `Submitter` object from a Dask cluster I've configured myself? This could enable the test issue to be resolved, and also provide more usability. It looks to be possible after glancing at `DaskWorker`: https://github.com/nipype/pydra/blob/acc90101af22637ff71139224441eacd08b14452/pydra/engine/workers.py#L315-L318
