### ISSUE TITLE
default values for FunctionTask

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#74]
We should think if this code should give pydra exception:

```
@pydra.to_task
def sum_a(a, b):
    return a + b
task = sum_a()
task()
```

**Comment by effigies** [comment]
Seems like it should produce an exception anyway. Does it not, currently?

**Comment by djarecka** [comment]
It takes `None` as a default, so in this specific example python will complain that doesn't know how to add Nones.  But I'm not sure if we want to take `None` as a default value.

**Comment by effigies** [comment]
My inclination would be "No", but I haven't given it much thought.

**Comment by djarecka** [comment]
I agree

**Comment by satra** [comment]
unlike nipype1, i would like to keep pydra as close to python as possible. with type checking and other things becoming optional addons. 

so the fact that it can take None and returns the standard python exception is fine with me.

nipype 2.0 can add type checking and undefined and other metadata on top.

**Comment by satra** [comment]
i don't know how you would differentiate between a keyword arg that is set to None vs someone providing None. this is why `Undefined` is special in traits.

**Comment by djarecka** [comment]
@satra - that was also my concern, and that's why I didn't try to change it right away.

We can keep it as an open issue, or if you think that there is no good option to differentiate and the python error is just fine, we can just close it
