### ISSUE TITLE
functions with multiple values in return statement

### ISSUE THREAD

**Issue by djarecka** [nipype/pydra#75]
If default `out` for output is used (without defining `output_names` - will be in pr) and a function returns two values, only one value is saved. See:

```
@pydra.to_task
def add_vector(x1, y1, x2, y2):
    return (x1 + x2, y1 + y2)

task5 = add_vector(name="add_vect", 
                   x1=[10, 20], y1=[1, 2], x2=[10, 20, 30], y2=[10, 20, 30])
task5.split(splitter=[("x1", "y1"), ("x2", "y2")])
task5(plugin="cf")
task5.result()
```

**Comment by satra** [comment]
the out values should be a tuple.

**Comment by djarecka** [comment]
but it's not right now...

**Comment by satra** [comment]
that should be fixed. given the code, i'm not sure why it wouldn't be:

https://github.com/nipype/pydra/blob/master/pydra/engine/task.py#L132

**Comment by djarecka** [comment]
I'm not sure yet, but it seems that it's not enough to ask for `ty.Any` [here](https://github.com/nipype/pydra/blob/master/pydra/engine/task.py#L96).
If `fields` have one element, only the first value will be saved
