### ISSUE TITLE
CI: Test on Windows

### ISSUE THREAD

**Issue by effigies** [nipype/pydra#83]
As noted in https://github.com/nipype/pydra/pull/81#discussion_r304493947, I would suggest that we try out [Azure Pipelines](https://github.com/marketplace/azure-pipelines) instead of AppVeyor.

Perhaps a good first step is somebody with access to a Windows computer to try to run the tests and estimate how big a job it is going to be to get us to compatibility. If that's going to be the struggle, learning a new CI infrastructure might be too much to add on top of it.

**Comment by satra** [comment]
this should also use the new bot.

**Comment by djarecka** [comment]
@satra - do we have any windows in the lab? or you just want me to go right to the Azure pipeline?

**Comment by satra** [comment]
not that i know of. yes, straight to azure - i hear it may also do OSX testing.

**Comment by effigies** [comment]
Nibabel uses these two files to configure Azure:

* https://github.com/nipy/nibabel/blob/master/azure-pipelines.yml
* https://github.com/nipy/nibabel/blob/master/.azure-pipelines/windows.yml

The second is a template for a run script. The first parameterizes variables over that template.

And yes, I believe it does OSX and Ubuntu as well as Windows. Travis also does OSX, which might be a lighter lift.

**Comment by djarecka** [comment]
ok, I can try to set azure, but if something needs debugging, we would need someone with windows machine
